apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-pipeline
  namespace: openshift-logging
data:
  fluent.conf: |
    ##################################
    # Define inputs for each channel #
    ##################################

    #log level: trace, debug, info, warn, error, fatal

    <source>
      @label application
      @log_level debug
      @type  forward
      port  24224
    </source>

    <source>
      @label infrastructure
      @log_level warn
      @type  forward
      port  24225
    </source>

    <source>
      @label audit
      @log_level trace
      @type  forward
      port  24226
    </source>

    ##################
    # Define filters #
    ##################

    #Add filter here
    <label @application>
    </label>

    #Add filter here
    <label @infrastructure>
    </label>

    #Add filter here
    <label @audit>
      #Only message containing "cool" in field "message"
      <filter **>
        @type grep
        <regexp>
          key message
          pattern /impossible fluentd pattern qozfuboqz/
        </regexp>
      </filter>
    </label>

    #######################
    # Define outputs here #
    #######################

    <match **>
      #https://github.com/fluent/fluent-plugin-splunk/blob/master/README.hec.md
      @type splunk_hec
      host "#{ENV[SPLUNK_URL]}"
      port "#{ENV[SPLUNK_PORT]}"
      token "#{ENV[SPLUNK_TOKEN]}"
    </match>

    # Uncomment to enable output to stdout
    # <match **>
    #   @type stdout
    # </match>
