apiVersion: v1
kind: ConfigMap
metadata:
  name: forwarder-fluentd-pipeline
  namespace: openshift-logging
  labels:
    app: forwarderFluentd
    app.kubernetes.io/component: forwarderFluentd
    app.kubernetes.io/instance: forwarderFluentd
data:
  fluent.conf: |
    ##################################
    # Define inputs for each channel #
    ##################################

    #log level: unknown, trace, debug, info, warn, error, fatal

    <source>
      tag source.pipeline.application
      # @log_level debug # Don't work, use filter grep exclude/regexp with key level
      @type  forward
      bind 0.0.0.0
      port  24284
    </source>

    <source>
      tag source.pipeline.infrastructure
      # @log_level error # Don't work, use filter grep exclude/regexp with key level
      @type  forward
      bind 0.0.0.0
      port  24285
    </source>

    <source>
      tag source.pipeline.audit
      # @log_level trace # Don't work, use filter grep exclude/regexp with key level
      @type  forward
      bind 0.0.0.0
      port  24286
    </source>

    ##################
    # Define filters #
    ##################

    #Add filter here
    # <filter source.pipeline.application>
    #   @type grep
    #   <regexp>
    #     key level
    #     pattern /^(unknown|trace|debug|info|warn|error|fatal)$/
    #   </regexp>
    # </filter>

    #Add filter here
    <filter source.pipeline.infrastructure>
      @type grep
      <regexp>
        key level
        pattern /^(error|fatal)$/
      </regexp>
    </filter>

    #Add filter here
    <filter source.pipeline.audit>
      @type grep
      <exclude>
        key $.user.username
        pattern /system/
      </exclude>
    </filter>
    <filter source.pipeline.audit>
      @type grep
      <exclude>
        key $.verb
        pattern /(get|list|watch)/
      </exclude>
    </filter>

    #######################
    # Define outputs here #
    #######################

    <match **>
      @type splunk_hec
      protocol "https"
      insecure_ssl "true"
      hec_host "#{ENV['SPLUNK_URL']}"
      sourcetype "openshift"
      source "openshift"
      index "openshift"
      hec_port "#{ENV['SPLUNK_PORT']}"
      hec_token "#{ENV['SPLUNK_TOKEN']}"
      host "openshift"
      <buffer>
        @type memory
        chunk_limit_records 100000
        chunk_limit_size 200m
        flush_interval 5s
        flush_thread_count 1
        overflow_action block
        retry_max_times 3
        total_limit_size 600m
      </buffer>
    </match>

    # Uncomment to enable output to stdout
    # <match **>
    #   @type stdout
    # </match>
