apiVersion: apps/v1
kind: Deployment
metadata:
  name: forwarder-fluentd
  namespace: openshift-logging
  labels:
    app: forwarderFluentd
    app.kubernetes.io/component: forwarderFluentd
    app.kubernetes.io/instance: forwarderFluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: forwarderFluentd
  template:
    metadata:
      labels:
        deployment: forwarderFluentd
        app: forwarderFluentd
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-logging-fluentd
          name: fluentd-forwarder
          ports:
            - containerPort: 24284
              protocol: TCP
            - containerPort: 24285
              protocol: TCP
            - containerPort: 24286
              protocol: TCP
          env:
            - name: SPLUNK_URL
              valueFrom:
                configMapKeyRef:
                  name: forwarder-splunk-config
                  key: url
            - name: SPLUNK_PORT
              valueFrom:
                configMapKeyRef:
                  name: forwarder-splunk-config
                  key: port
            - name: SPLUNK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: forwarder-splunk-token
                  key: token
            - name: FLUENT_CONF
              value: "/fluentd/etc/fluent.conf"
          volumeMounts:
          - name: config
            mountPath: /etc/fluent/configs.d/user	
          - name: entrypoint
            mountPath: /opt/app-root/src/
            subpath: run.sh
          - name: varlib
            mountPath: /var/lib/fluentd
      volumes:
        - name: config
          configMap: 
            name: forwarder-fluentd-pipeline
        - name: entrypoint
          configMap:
            name: forwarder-fluentd-runsh
        - name: varlib
          emptyDir:
            sizeLimit: 500Mi