apiVersion: v1
kind: Service
metadata:
  name: forwarder-fluentd
  namespace: openshift-logging
  labels:
    app: forwarderFluentd
    app.kubernetes.io/component: forwarderFluentd
    app.kubernetes.io/instance: forwarderFluentd
spec:
  selector:
    app: forwarderFluentd
  ports:
  - port: 24284
    protocol: TCP
    targetPort: 24284
    name: application
  - port: 24285
    protocol: TCP
    targetPort: 24285
    name: infrastructure
  - port: 24286
    protocol: TCP
    targetPort: 24286
    name: audit