apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - name: application-fluentdForwarder
      type: fluentdForward
      url: 'tcp://fluentd-forwarder.openshift-logging.svc.cluster.local:24284/'
    - name: infrastructure-fluentdForwarder
      type: fluentdForward
      url: 'tcp://fluentd-forwarder.openshift-logging.svc.cluster.local:24285/'
    - name: audit-fluentdForwarder
      type: fluentdForward
      url: 'tcp://fluentd-forwarder.openshift-logging.svc.cluster.local:24286/'
  pipelines:
    - name: application-to-fluentdForwarder
      inputRefs:
        - application
      outputRefs:
        - application-fluentdForwarder
    - name: infrastructure-to-fluentdForwarder
      inputRefs:
        - infrastructure
      outputRefs:
        - infrastructure-fluentdForwarder
    - name: audit-to-fluentdForwarder
      inputRefs:
        - audit
      outputRefs:
        - audit-fluentdForwarder