apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - name: fluentd-application
      type: fluentdForward
      url: 'tcp://forwarder-fluentd.openshift-logging.svc.cluster.local:24284/'
    - name: fluentd-infrastructure
      type: fluentdForward
      url: 'tcp://forwarder-fluentd.openshift-logging.svc.cluster.local:24285/'
    - name: fluentd-audit
      type: fluentdForward
      url: 'tcp://forwarder-fluentd.openshift-logging.svc.cluster.local:24286/'
  pipelines:
    - name: application
      inputRefs:
        - application
      outputRefs:
        - fluentd-application
    - name: infrastructure
      inputRefs:
        - infrastructure
      outputRefs:
        - fluentd-infrastructure
    - name: audit
      inputRefs:
        - audit
      outputRefs:
        - fluentd-audit