apiVersion: v1
kind: ConfigMap
metadata:
  name: forwarder-splunk-config
  namespace: openshift-logging
  labels:
    app: forwarder
    app.kubernetes.io/component: forwarder
    app.kubernetes.io/instance: forwarder
data:
  url: "temporary url"
  port: "8080"