apiVersion: v1
kind: Secret
metadata:
  name: forwarder-splunk-token
  namespace: openshift-logging
data:
  # Values must be base64 encoded
  # Here is: "Temporary Token"
  token: "VGVtcG9yYXJ5IFRva2VuCg=="