apiVersion: v1
kind: Secret
metadata:
  name: forwarder-splunk-token
  namespace: openshift-logging
  labels:
    app: forwarder
    app.kubernetes.io/component: forwarder
    app.kubernetes.io/instance: forwarder
data:
  # Values must be base64 encoded
  # Here is: "Temporary Token"
  token: "VGVtcG9yYXJ5IFRva2VuCg=="