apiVersion: v1
kind: ConfigMap
metadata:
  name: forwarder-logstash-pipeline
  namespace: openshift-logging
  labels:
    app: forwarder
    appVersion: logstash
    app.kubernetes.io/component: forwarderLogstash
    app.kubernetes.io/instance: forwarderLogstash
data:
  filter.conf: |
    input {
      tcp {
        tags => ["application"]
        port => "5044"
        type => syslog
      }
      tcp {
        tags => ["infrastructure"]
        port => "5045"
        type => syslog
      }
      tcp {
        tags => ["audit"]
        port => "5046"
        type => syslog
      }
    }

    filter {
      if "application" in [tags] {
        #Need filter here
      }
      if "infrastructure" in [tags] {
        #Need filter here
      }
      if "audit" in [tags] {
        # # First simple format
        # ruby {
        #   path => "/usr/share/logstash/ruby/format-simple.rb"
        # }
        # # Format message in fields
        # kv {
        #   source => "message"
        #   field_split_pattern => "\t"
        #   value_split => ":"
        #   target => "message"
        # }

        # # Second deeper format
        # ruby {
        #   path => "/usr/share/logstash/ruby/format-deep.rb"
        # }

        #Need filter here
        drop {}
      }
    }

    output {
      http {
        http_method => "post"
        url => "${SPLUNK_URL}:${SPLUNK_PORT}"
        headers => ["Authorization", "Splunk ${SPLUNK_TOKEN}"]
        mapping => {
          "event" => "%{log}"
        }
      }

      # Uncomment to enable output to stdout
      # stdout {}
    }