apiVersion: v1
kind: ConfigMap
metadata:
  name: forwarder-logstash-pipeline
  namespace: openshift-logging
data:
  filter.conf: |
    input {
      tcp {
        tags => ["application"]
        port => "5044"
        type => syslog
      }
      tcp {
        tags => ["infrastructure"]
        port => "5045"
        type => syslog
      }
      tcp {
        tags => ["audit"]
        port => "5046"
        type => syslog
      }
    }

    filter {
      if "application" in [tags] {
        #Need filter here
      }
      if "infrastructure" in [tags] {
        #Need filter here
      }
      if "audit" in [tags] {
        #Need filter here
        drop {}
      }
    }

    output {
      http {
        http_method => "post"
        url => "${SPLUNK_URL}:${SPLUNK_PORT}"
        headers => ["Authorization", "Splunk ${SPLUNK_TOKEN}"]
        mapping => {
          "event" => "%{log}"
        }
      }

      # Uncomment to enable output to stdout
      # stdout {}
    }