apiVersion: v1
kind: ConfigMap
metadata:
  name: forwarder-logstash-pipeline
  namespace: openshift-logging
  labels:
    app: forwarder
    appVersion: logstash
    app.kubernetes.io/component: forwarderLogstash
    app.kubernetes.io/instance: forwarderLogstash
data:
  filter.conf: |
    input {
      tcp {
        tags => ["application"]
        port => "5044"
        type => syslog
      }
      tcp {
        tags => ["infrastructure"]
        port => "5045"
        type => syslog
      }
      tcp {
        tags => ["audit"]
        port => "5046"
        type => syslog
      }
    }

    filter {
      ruby {
        path => "/user/share/logstash/ruby/format-message.rb"
      }

      if "application" in [tags] {
        #Need filter here
      }
      if "infrastructure" in [tags] {
        #Need filter here
      }
      if "audit" in [tags] {
        #Need filter here
        drop {}
      }
    }

    output {
      # http {
      #   format => "json"
      #   content_type => "application/json"
      #   http_method => "post"
      #   url => "https://${SPLUNK_URL}:${SPLUNK_PORT}/services/collector/raw"
      #   headers => ["Authorization", "Splunk ${SPLUNK_TOKEN}"]
      #   mapping => {
      #     "event" => "%{message}"
      #   }
      # }

      # Uncomment to enable output to stdout
      stdout {}
    }