apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-ruby
  namespace: openshift-logging
data:
  main.rb: |
    def filter(event)
      #get the message field
      message = event.get("message")

      # regexp
      debut = message[/.* .* (.* .*) - - - .*/, 1]
      formate = message[/.* - - - (.*)/, 1]

      # replace @timestamp with timestamp
      formate.sub! '@timestamp', 'timestamp'

      # replace message with custom value
      event.set("message", "pod:"+debut+"\t"+formate)

      #return the event in a list
      return [event]
    end