apiVersion: apps/v1
kind: Deployment
metadata:
  name: forwarder-logstash
  namespace: openshift-logging
  labels:
    app: forwarderLogstash
    app.kubernetes.io/component: forwarderLogstash
    app.kubernetes.io/instance: forwarderLogstash
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: forwarderLogstash
  template:
    metadata:
      labels:
        deployment: forwarderLogstash
        app: forwarderLogstash
    spec:
      containers:
        - image: docker.elastic.co/logstash/logstash
          name: forwarder-logstash
          ports:
            - containerPort: 5044
              protocol: TCP
            - containerPort: 5045
              protocol: TCP
            - containerPort: 5046
              protocol: TCP
          env:
            - name: SPLUNK_URL
              valueFrom:
                configMapKeyRef:
                  name: splunk-config
                  key: url
            - name: SPLUNK_PORT
              valueFrom:
                configMapKeyRef:
                  name: splunk-config
                  key: port
            - name: SPLUNK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: splunk-token
                  key: token
          volumeMounts:
          - name: pipeline
            mountPath: /usr/share/logstash/pipeline/
          - name: config
            mountPath: /usr/share/logstash/config/
      volumes:
        - name: pipeline
          configMap: 
            name: forwarder-logstash-pipeline
        - name: config
          configMap: 
            name: forwarder-logstash-config