apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: openshift-logging
  labels:
    app: logstash
    app.kubernetes.io/component: logstash
    app.kubernetes.io/instance: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: logstash
  template:
    metadata:
      labels:
        deployment: logstash
        app: logstash
    spec:
      containers:
        - image: docker.elastic.co/logstash/logstash:7.11.1
          name: logstash
          ports:
            - containerPort: 5044
              protocol: TCP
            - containerPort: 5045
              protocol: TCP
            - containerPort: 5046
              protocol: TCP
          env:
            - name: SPLUNK_URL
              valueFrom:
                configMapKeyRef:
                  name: splunk-config
                  key: url
            - name: SPLUNK_PORT
              valueFrom:
                configMapKeyRef:
                  name: splunk-config
                  key: port
            - name: SPLUNK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: splunk-token
                  key: token
          volumeMounts:
          - name: pipeline
            mountPath: /usr/share/logstash/pipeline/
          - name: config
            mountPath: /usr/share/logstash/config/
      volumes:
        - name: pipeline
          configMap: 
            name: logstash-pipeline
        - name: config
          configMap: 
            name: logstash-config